language: python
python:
  - "3.6"
# command to install dependencies
cache: pip3

install:
  - pip install git+https://github.com/UBC-MDS/AudioFilters_py@master
  - pip install -r requirements.txt
  - pip install -U pytest
  - pip install numpy
  - pip install librosa

# command to run tests
script:
  - cd tests/
  - pytest
