language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U pytest
  - pip install numpy
  - pip install librosa

# command to run tests
script:
  - pytest
